name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: DeLaGuardo/setup-clojure@3.5
      with:
        cli: 1.11.1.1113

    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          ~/.gitlibs
          ~/.m2
        key: ${{ runner.os }}-${{ hashFiles('deps.edn') }}

    - uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Install dependencies
      run: clojure -X:deps prep
    - name: Lint code
      run: clojure -M:clj-kondo --lint src
    - name: Generate
      run: clojure -X:gen
    - name: Compile
      run: clojure -T:build compile
    - name: Package
      run: clojure -T:build package
    - name: Deploy
      run: gcloud app deploy target/reuz-standalone.jar
