name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: DeLaGuardo/setup-clojure@7.0
      with:
        cli: 1.11.1.1139

    - uses: actions/checkout@v3.0.2

    - uses: actions/cache@v3.0.4
      with:
        path: |
          ~/.gitlibs
          ~/.m2
        key: ${{ runner.os }}-${{ hashFiles('deps.edn') }}

    - uses: google-github-actions/setup-gcloud@v0.6.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Install dependencies
      run: clojure -X:deps prep
    - name: Check code format
      run: clojure -M:cljfmt check .
    - name: Lint code
      run: clojure -M:clj-kondo --lint .
    - name: Compile
      run: clojure -T:build compile
    - name: Package
      run: clojure -T:build package
    - name: Deploy
      run: gcloud app deploy target/reuz-standalone.jar
